repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: ty
        language: python
        additional_dependencies: ["ty==0.0.15"]
        pass_filenames: false
        args: ["check", "src"]
        files: ^src/.*\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
      - id: nbqa-ruff
        args:
          - --fix
          - --config=pyproject.toml
          - --extend-ignore=B018,B015,E501
        additional_dependencies: ["ruff==0.6.8"]
        files: \.ipynb$
      - id: nbqa
        name: nbqa-ty
        entry: nbqa
        args: ["ty", "check"]
        additional_dependencies: ["ty==0.0.15"]
        files: \.ipynb$


  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        files: \.ipynb$
        args:
          - --extra-keys
          - "metadata.kernelspec metadata.language_info"
